# Generated by Django 5.2.4 on 2025-07-20 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the healthcare institution.', max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the institution.')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'healthcare institution',
                'verbose_name_plural': 'healthcare institutions',
            },
        ),
    ]
