# Generated by Django 5.2.4 on 2025-07-20 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date_time', models.DateTimeField(help_text='Date and time of the appointment.')),
                ('reason', models.TextField(blank=True, help_text='Reason for the appointment.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the appointment.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='The healthcare institution where the appointment is scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='institutions.healthcareinstitution')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['appointment_date_time'],
            },
        ),
    ]
