# Generated by Django 5.2.4 on 2025-07-20 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, help_text="Patient's date of birth.", null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text="Patient's sex.", max_length=10)),
                ('allergies', models.TextField(blank=True, help_text="Patient's known allergies.")),
                ('current_medications', models.TextField(blank=True, help_text='Currently prescribed medications.')),
                ('past_medical_history', models.TextField(blank=True, help_text='Significant past medical conditions and surgeries.')),
                ('family_medical_history', models.TextField(blank=True, help_text='Relevant family medical history.')),
                ('immunization_history', models.TextField(blank=True, help_text='Record of immunizations.')),
                ('blood_type', models.CharField(blank=True, help_text="Patient's blood type.", max_length=5)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's height in centimeters.", max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Patient's weight in kilograms.", max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this medical record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(help_text='The patient associated with this medical record.', limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The last user who updated this medical record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient medical record',
                'verbose_name_plural': 'patient medical records',
            },
        ),
    ]
